-- Inserindo os municipios goianos
INSERT INTO municipio (nome) VALUES('Goiânia');
INSERT INTO municipio (nome) VALUES('Aparecida de Goiânia');
INSERT INTO municipio (nome) VALUES('Anápolis');
INSERT INTO municipio (nome) VALUES('Rio Verde');
INSERT INTO municipio (nome) VALUES('Águas Lindas de Goiás');
INSERT INTO municipio (nome) VALUES('Valparaíso de Goiás');
INSERT INTO municipio (nome) VALUES('Luziânia');
INSERT INTO municipio (nome) VALUES('Senador Canedo');
INSERT INTO municipio (nome) VALUES('Trindade');
INSERT INTO municipio (nome) VALUES('Itumbiara');
INSERT INTO municipio (nome) VALUES('Formosa');
INSERT INTO municipio (nome) VALUES('Catalão');
INSERT INTO municipio (nome) VALUES('Planaltina');
INSERT INTO municipio (nome) VALUES('Jataí');
INSERT INTO municipio (nome) VALUES('Novo Gama');
INSERT INTO municipio (nome) VALUES('Caldas Novas');
INSERT INTO municipio (nome) VALUES('Cidade Ocidental');
INSERT INTO municipio (nome) VALUES('Goianésia');
INSERT INTO municipio (nome) VALUES('Mineiros');
INSERT INTO municipio (nome) VALUES('Goianira');
INSERT INTO municipio (nome) VALUES('Santo Antônio do Descoberto');
INSERT INTO municipio (nome) VALUES('Cristalina');
INSERT INTO municipio (nome) VALUES('Inhumas');
INSERT INTO municipio (nome) VALUES('Quirinópolis');
INSERT INTO municipio (nome) VALUES('Morrinhos');
INSERT INTO municipio (nome) VALUES('Itaberaí');
INSERT INTO municipio (nome) VALUES('Porangatu');
INSERT INTO municipio (nome) VALUES('Jaraguá');
INSERT INTO municipio (nome) VALUES('Uruaçu');
INSERT INTO municipio (nome) VALUES('Santa Helena de Goiás');
INSERT INTO municipio (nome) VALUES('Goiatuba');
INSERT INTO municipio (nome) VALUES('Niquelândia');
INSERT INTO municipio (nome) VALUES('Iporá');
INSERT INTO municipio (nome) VALUES('Posse');
INSERT INTO municipio (nome) VALUES('Padre Bernardo');
INSERT INTO municipio (nome) VALUES('Bela Vista de Goiás');
INSERT INTO municipio (nome) VALUES('Nerópolis');
INSERT INTO municipio (nome) VALUES('São Luís de Montes Belos');
INSERT INTO municipio (nome) VALUES('Pires do Rio');
INSERT INTO municipio (nome) VALUES('Palmeiras de Goiás');
INSERT INTO municipio (nome) VALUES('Alexânia');
INSERT INTO municipio (nome) VALUES('Itapuranga');
INSERT INTO municipio (nome) VALUES('Hidrolândia');
INSERT INTO municipio (nome) VALUES('Minaçu');
INSERT INTO municipio (nome) VALUES('Pirenópolis');
INSERT INTO municipio (nome) VALUES('Ipameri');
INSERT INTO municipio (nome) VALUES('Cocalzinho de Goiás');
INSERT INTO municipio (nome) VALUES('Piracanjuba');
INSERT INTO municipio (nome) VALUES('Goiás');
INSERT INTO municipio (nome) VALUES('São Miguel do Araguaia');
INSERT INTO municipio (nome) VALUES('Bom Jesus de Goiás');
INSERT INTO municipio (nome) VALUES('Silvânia');
INSERT INTO municipio (nome) VALUES('Ceres');
INSERT INTO municipio (nome) VALUES('Itapaci');
INSERT INTO municipio (nome) VALUES('Acreúna');
INSERT INTO municipio (nome) VALUES('Crixás');
INSERT INTO municipio (nome) VALUES('Rubiataba');
INSERT INTO municipio (nome) VALUES('Anicuns');
INSERT INTO municipio (nome) VALUES('Jussara');
INSERT INTO municipio (nome) VALUES('Abadia de Goiás');
INSERT INTO municipio (nome) VALUES('Pontalina');
INSERT INTO municipio (nome) VALUES('Campos Belos');
INSERT INTO municipio (nome) VALUES('Aragarças');
INSERT INTO municipio (nome) VALUES('São Simão');
INSERT INTO municipio (nome) VALUES('Guapó');
INSERT INTO municipio (nome) VALUES('Caiapônia');
INSERT INTO municipio (nome) VALUES('Indiara');
INSERT INTO municipio (nome) VALUES('Orizona');
INSERT INTO municipio (nome) VALUES('Abadiânia');
INSERT INTO municipio (nome) VALUES('Mozarlândia');
INSERT INTO municipio (nome) VALUES('Caçu');
INSERT INTO municipio (nome) VALUES('Vianópolis');
INSERT INTO municipio (nome) VALUES('Goianápolis');
INSERT INTO municipio (nome) VALUES('Uruana');
INSERT INTO municipio (nome) VALUES('Nova Crixás');
INSERT INTO municipio (nome) VALUES('Chapadão do Céu');
INSERT INTO municipio (nome) VALUES('Campinorte');
INSERT INTO municipio (nome) VALUES('Montividiu');
INSERT INTO municipio (nome) VALUES('Edéia');
INSERT INTO municipio (nome) VALUES('Cachoeira Alta');
INSERT INTO municipio (nome) VALUES('Rialma');
INSERT INTO municipio (nome) VALUES('Flores de Goiás');
INSERT INTO municipio (nome) VALUES('Aragoiânia');
INSERT INTO municipio (nome) VALUES('Piranhas');
INSERT INTO municipio (nome) VALUES('Iaciara');
INSERT INTO municipio (nome) VALUES('São João d''Aliança');
INSERT INTO municipio (nome) VALUES('Barro Alto');
INSERT INTO municipio (nome) VALUES('Cavalcante');
INSERT INTO municipio (nome) VALUES('Buriti Alegre');
INSERT INTO municipio (nome) VALUES('Mara Rosa');
INSERT INTO municipio (nome) VALUES('Alto Paraíso de Goiás');
INSERT INTO municipio (nome) VALUES('Paraúna');
INSERT INTO municipio (nome) VALUES('Santa Terezinha de Goiás');
INSERT INTO municipio (nome) VALUES('Bonfinópolis');
INSERT INTO municipio (nome) VALUES('Firminópolis');
INSERT INTO municipio (nome) VALUES('Corumbá de Goiás');
INSERT INTO municipio (nome) VALUES('São Domingos');
INSERT INTO municipio (nome) VALUES('Maurilândia');
INSERT INTO municipio (nome) VALUES('Montes Claros de Goiás');
INSERT INTO municipio (nome) VALUES('Paranaiguara');
INSERT INTO municipio (nome) VALUES('Carmo do Rio Verde');
INSERT INTO municipio (nome) VALUES('Nazário');
INSERT INTO municipio (nome) VALUES('Nova Veneza');
INSERT INTO municipio (nome) VALUES('Petrolina de Goiás');
INSERT INTO municipio (nome) VALUES('Leopoldo de Bulhões');
INSERT INTO municipio (nome) VALUES('Vicentinópolis');
INSERT INTO municipio (nome) VALUES('Corumbaíba');
INSERT INTO municipio (nome) VALUES('Itauçu');
INSERT INTO municipio (nome) VALUES('Alvorada do Norte');
INSERT INTO municipio (nome) VALUES('Nova Glória');
INSERT INTO municipio (nome) VALUES('Sanclerlândia');
INSERT INTO municipio (nome) VALUES('Serranópolis');
INSERT INTO municipio (nome) VALUES('Mambaí');
INSERT INTO municipio (nome) VALUES('Aruanã');
INSERT INTO municipio (nome) VALUES('Campo Limpo de Goiás');
INSERT INTO municipio (nome) VALUES('Itapirapuã');
INSERT INTO municipio (nome) VALUES('Terezópolis de Goiás');
INSERT INTO municipio (nome) VALUES('Cezarina');
INSERT INTO municipio (nome) VALUES('Bom Jardim de Goiás');
INSERT INTO municipio (nome) VALUES('Cachoeira Dourada');
INSERT INTO municipio (nome) VALUES('Santo Antônio de Goiás');
INSERT INTO municipio (nome) VALUES('Campo Alegre de Goiás');
INSERT INTO municipio (nome) VALUES('Cabeceiras');
INSERT INTO municipio (nome) VALUES('Santa Rita do Araguaia');
INSERT INTO municipio (nome) VALUES('Ouvidor');
INSERT INTO municipio (nome) VALUES('Joviânia');
INSERT INTO municipio (nome) VALUES('Faina');
INSERT INTO municipio (nome) VALUES('Itarumã');
INSERT INTO municipio (nome) VALUES('Araguapaz');
INSERT INTO municipio (nome) VALUES('Doverlândia');
INSERT INTO municipio (nome) VALUES('Monte Alegre de Goiás');
INSERT INTO municipio (nome) VALUES('Jandaia');
INSERT INTO municipio (nome) VALUES('Mundo Novo');
INSERT INTO municipio (nome) VALUES('Santa Bárbara de Goiás');
INSERT INTO municipio (nome) VALUES('Alto Horizonte');
INSERT INTO municipio (nome) VALUES('Britânia');
INSERT INTO municipio (nome) VALUES('Inaciolândia');
INSERT INTO municipio (nome) VALUES('Fazenda Nova');
INSERT INTO municipio (nome) VALUES('Simolândia');
INSERT INTO municipio (nome) VALUES('Vila Propício');
INSERT INTO municipio (nome) VALUES('Água Fria de Goiás');
INSERT INTO municipio (nome) VALUES('Caturaí');
INSERT INTO municipio (nome) VALUES('Gouvelândia');
INSERT INTO municipio (nome) VALUES('Goiandira');
INSERT INTO municipio (nome) VALUES('Santa Fé de Goiás');
INSERT INTO municipio (nome) VALUES('São Luiz do Norte');
INSERT INTO municipio (nome) VALUES('Itaguari');
INSERT INTO municipio (nome) VALUES('Americano do Brasil');
INSERT INTO municipio (nome) VALUES('Itaguaru');
INSERT INTO municipio (nome) VALUES('Hidrolina');
INSERT INTO municipio (nome) VALUES('Turvelândia');
INSERT INTO municipio (nome) VALUES('Mossâmedes');
INSERT INTO municipio (nome) VALUES('Formoso');
INSERT INTO municipio (nome) VALUES('Itajá');
INSERT INTO municipio (nome) VALUES('Turvânia');
INSERT INTO municipio (nome) VALUES('Caldazinha');
INSERT INTO municipio (nome) VALUES('Campos Verdes');
INSERT INTO municipio (nome) VALUES('Divinópolis de Goiás');
INSERT INTO municipio (nome) VALUES('Santo Antônio da Barra');
INSERT INTO municipio (nome) VALUES('São Miguel do Passa-Quatro');
INSERT INTO municipio (nome) VALUES('Porteirão');
INSERT INTO municipio (nome) VALUES('Aporé');
INSERT INTO municipio (nome) VALUES('Ouro Verde de Goiás');
INSERT INTO municipio (nome) VALUES('Matrinchã');
INSERT INTO municipio (nome) VALUES('Taquaral de Goiás');
INSERT INTO municipio (nome) VALUES('Guarani de Goiás');
INSERT INTO municipio (nome) VALUES('Brazabrantes');
INSERT INTO municipio (nome) VALUES('Rianápolis');
INSERT INTO municipio (nome) VALUES('Colinas do Sul');
INSERT INTO municipio (nome) VALUES('Rio Quente');
INSERT INTO municipio (nome) VALUES('Cromínia');
INSERT INTO municipio (nome) VALUES('Edealina');
INSERT INTO municipio (nome) VALUES('Uirapuru');
INSERT INTO municipio (nome) VALUES('Araçu');
INSERT INTO municipio (nome) VALUES('Palminópolis');
INSERT INTO municipio (nome) VALUES('Amaralina');
INSERT INTO municipio (nome) VALUES('Damianópolis');
INSERT INTO municipio (nome) VALUES('Campestre de Goiás');
INSERT INTO municipio (nome) VALUES('Varjão');
INSERT INTO municipio (nome) VALUES('Campinaçu');
INSERT INTO municipio (nome) VALUES('Novo Planalto');
INSERT INTO municipio (nome) VALUES('Vila Boa');
INSERT INTO municipio (nome) VALUES('Cristianópolis');
INSERT INTO municipio (nome) VALUES('Montividiu do Norte');
INSERT INTO municipio (nome) VALUES('Mutunópolis');
INSERT INTO municipio (nome) VALUES('Santa Isabel');
INSERT INTO municipio (nome) VALUES('Palestina de Goiás');
INSERT INTO municipio (nome) VALUES('Gameleira de Goiás');
INSERT INTO municipio (nome) VALUES('Aurilândia');
INSERT INTO municipio (nome) VALUES('Baliza');
INSERT INTO municipio (nome) VALUES('Professor Jamil');
INSERT INTO municipio (nome) VALUES('Santa Tereza de Goiás');
INSERT INTO municipio (nome) VALUES('Portelândia');
INSERT INTO municipio (nome) VALUES('Estrela do Norte');
INSERT INTO municipio (nome) VALUES('Perolândia');
INSERT INTO municipio (nome) VALUES('Bonópolis');
INSERT INTO municipio (nome) VALUES('Heitoraí');
INSERT INTO municipio (nome) VALUES('Trombas');
INSERT INTO municipio (nome) VALUES('Urutaí');
INSERT INTO municipio (nome) VALUES('Buritinópolis');
INSERT INTO municipio (nome) VALUES('Santa Cruz de Goiás');
INSERT INTO municipio (nome) VALUES('Nova Roma');
INSERT INTO municipio (nome) VALUES('Nova Iguaçu de Goiás');
INSERT INTO municipio (nome) VALUES('Amorinópolis');
INSERT INTO municipio (nome) VALUES('Castelândia');
INSERT INTO municipio (nome) VALUES('Panamá');
INSERT INTO municipio (nome) VALUES('Arenópolis');
INSERT INTO municipio (nome) VALUES('Santa Rita do Novo Destino');
INSERT INTO municipio (nome) VALUES('Sítio d''Abadia');
INSERT INTO municipio (nome) VALUES('Jaupaci');
INSERT INTO municipio (nome) VALUES('Aparecida do Rio Doce');
INSERT INTO municipio (nome) VALUES('Cumari');
INSERT INTO municipio (nome) VALUES('Ipiranga de Goiás');
INSERT INTO municipio (nome) VALUES('Três Ranchos');
INSERT INTO municipio (nome) VALUES('Santa Rosa de Goiás');
INSERT INTO municipio (nome) VALUES('Damolândia');
INSERT INTO municipio (nome) VALUES('Buriti de Goiás');
INSERT INTO municipio (nome) VALUES('Teresina de Goiás');
INSERT INTO municipio (nome) VALUES('Marzagão');
INSERT INTO municipio (nome) VALUES('Ivolândia');
INSERT INTO municipio (nome) VALUES('Mimoso de Goiás');
INSERT INTO municipio (nome) VALUES('Israelândia');
INSERT INTO municipio (nome) VALUES('Mairipotaba');
INSERT INTO municipio (nome) VALUES('Avelinópolis');
INSERT INTO municipio (nome) VALUES('Morro Agudo de Goiás');
INSERT INTO municipio (nome) VALUES('Córrego do Ouro');
INSERT INTO municipio (nome) VALUES('Adelândia');
INSERT INTO municipio (nome) VALUES('Pilar de Goiás');
INSERT INTO municipio (nome) VALUES('Palmelo');
INSERT INTO municipio (nome) VALUES('Nova América');
INSERT INTO municipio (nome) VALUES('Guaraíta');
INSERT INTO municipio (nome) VALUES('Guarinos');
INSERT INTO municipio (nome) VALUES('São Patrício');
INSERT INTO municipio (nome) VALUES('Jesúpolis');
INSERT INTO municipio (nome) VALUES('Nova Aurora');
INSERT INTO municipio (nome) VALUES('Diorama');
INSERT INTO municipio (nome) VALUES('São João da Paraúna');
INSERT INTO municipio (nome) VALUES('Aloândia');
INSERT INTO municipio (nome) VALUES('Água Limpa');
INSERT INTO municipio (nome) VALUES('Davinópolis');
INSERT INTO municipio (nome) VALUES('Moiporá');
INSERT INTO municipio (nome) VALUES('Lagoa Santa');
INSERT INTO municipio (nome) VALUES('Cachoeira de Goiás');
INSERT INTO municipio (nome) VALUES('Anhanguera');